docker: /var/run/docker.sock
daemonize: false
interval: 5000
ttl: 12000
path:
- string:services
- environment:ENVIRONMENT
- environment:APP
- environment:NAME
- container:HOSTNAME
backend: etcd
backends:
  zookeeper:
    uri: zk://localhost:2181
  etcd:
    host: discovery
    port: 4001
